### PR TITLE
Add a predicate parser

### PR DESCRIPTION
**Pull request by arseniiv**
This one adds a predicate parser, which is useful to match a general input literal partially, like matching a token by its type but not all other info which a token has.

Simple tests are included (I used the literal parser test case as a reference), and are passing.

What do you think? :slightly_smiling_face:

### CODE REVIEW

**Comment by drhagen** [comment]
I think this would be a great addition to Parsita. Thank you for proposing it. The only thing is that is always consumes only a single token, which makes it effectively useless in the TextParsers context. If this took a `Parser` as an additional argument, then it would be more generally useful.

I am thinking of a definition like this:
```
def pred(parser: Parser[Input, Output], predicate: Callable[[Output], bool], predicate_descr: str):
    ...
```

with usage like this:

```
number = reg("\d+")
percent = pred(number, lambda x: 0 <= x <= 100, "a number between 0 and 100")
```
or
```
pair = "[" >> number << "," & number << "]"
interval = pred(pair, lamba x: x[0] <= x[1], "x <= y")
```

Now, to make it easy in the case of consuming a single token, we should add a new dummy parser called either `any` or `any1` that simply consumes a single token and returns it:

```
digit = pred(any1, str.isdigit, 'digit')
```

What do you think?

**Comment by arseniiv** [comment]
This is a great extension! I’ll implement it tomorrow, then. Also, I’ll see about `any` or `any1` too, I think.

**Comment by arseniiv** [comment]
Here’s what I think on these. For name, I picked `any1` in the end because there’s already an `any` in Python library. Though I haven’t added anything about new combinators to the readme… :thinking:

**Comment by arseniiv** [comment]
I agree! I would still add something else related to these parsers, but currently I don’t have new ideas in mind, so this is ok.

**Pull request merged**
